server:
  #网关端口8083
  port: 8083
spring:
  application:
    #在服务中心的应用名称
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #自动映射eureka下的服务路由
          enabled: true
          #开启服务名称小写
          lower-case-service-id: true
      routes:
        - id: client
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/client/**

# 注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
